Complete week1 progress
Sinica-SLAM/Intern-Training pull request #10
Opened 2021-07-18 10:23 UTC by txya900619

### Summary
- Add week1(ch1, ch2)  examples

### Todo
- [x] ch2 examples
- [x] ch3 examples

2021-07-18 10:39 UTC, jamfly requested changes

2021-07-18 10:39 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise1.py
> +def getRandomNaDataFrame(dataFrame: pd.DataFrame) -> pd.DataFrame:
pyhton 是用 _ 隔開，不是大駝峰，其他的也順便也改一下

2021-07-18 10:39 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise1.py
> +    with open("example_dataset.csv", "r") as f:
最好加一下 `encoding="utf-8"` 比較安全

2021-07-18 10:39 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise1.py
> +    with open("example_dataset.csv", "r") as f:
另外不要叫 f，要把什麼檔案的名稱寫清楚

2021-07-18 10:39 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise1.py
> +def getRandomNaDataFrame(dataFrame: pd.DataFrame) -> pd.DataFrame:
如果可以的話，是希望每個 function 也寫一下他在做啥，不過也許因為這只是練習所以可以不用寫

2021-07-18 10:39 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise1.py
> +    return dataFrame.mask(np.random.random(dataFrame.shape) < 0.2)
不要用 0.2 這個魔術數字，給他個名字吧

2021-07-18 10:39 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise2.py
> +from exercise1 import getRandomNaDataFrame, processData
import 也稍微排一下，FYI: http://seanlin.logdown.com/posts/238863-python-idioms-25-import-order

2021-07-18 10:39 UTC, jamfly commented on txya900619/Week1/ch2/2.3/exercise6.py
> +        "A and A.sum(axis=1) not match, because A.sum(axis=1) will reduce to shape (5) and when broadcasting to would be (1, 5), then (5, 4) not match to (1, 5)"
太長了，改用
```
print(
    "string 1"
    "string 2"
    "string 3"
)
```

2021-07-18 10:40 UTC, jamfly commented
@txya900619 README 記得填日期

2021-07-18 11:46 UTC, txya900619 commented
> @txya900619 README 記得填日期

好w

2021-07-18 16:58 UTC, jamfly requested changes

2021-07-18 16:58 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise1.py
> +    # random insert na to dataframe
如果是 function 的解釋的話要用 """Insert na to dataframe randomly""" 包住

2021-07-18 16:58 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise1.py
> +    naCount = dataFrame.isnull().sum(axis=0).tolist()
變數命名也是 _ 隔開，不是小駝峰

2021-07-18 16:58 UTC, jamfly commented on txya900619/Week1/ch2/2.2/exercise2.py
> +    with open("example_dataset.csv", "r") as f:
只要是 open 檔案的都可以順便改成上面那種形式

2021-07-19 03:08 UTC, jamfly approved these changes
LGTM!

2021-07-19 03:09 UTC, merged