finish week1
Sinica-SLAM/Intern-Training pull request #12
Opened 2021-07-21 12:53 UTC by U08410006

### Summary
> Week 1 ch2, ch3

### Todo
- [x] ch2
- [x] ch3

2021-07-21 13:16 UTC, jamfly requested changes
有滿多地方需要修改，大多數是格式。可以參考立委的檔案格式

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +import numpy as np
import 也稍微排一下，FYI: http://seanlin.logdown.com/posts/238863-python-idioms-25-import-order

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +def f(x):
function/parameter 名稱要取得有意義，不然過一週看你完全看不懂你在寫啥。
另外如果可以的話，在每個 function 底下都寫下這個 function 在幹嘛。
如果可以把 type 也寫上，那就更好了。如果不會的話可以參考 [立委的](https://github.com/Sinica-SLAM/Intern-Training/tree/main/txya900619/Week1)。

範例：
```
def add(first_number: int, second_number: int) -> int:
    """"Return first_number + second_number"""
   return first_number + second_number
```

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +def use_svg_display():  # @save
為什麼會一直出現 `# @save` ？

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +h = 0.1
不要出現 global variable，如果真的要 constant 。請使用 `THIS_IS_THE_CONSTANT = 1` 並且放在程式的開頭。

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +for i in range(5):
如果 i 沒有用到，可以用 _ 。並且命名都要再注意，需要更有 context 不然很難幫助別人理解這段扣在做什麼。

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +    set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)
盡量不要使用這種 inplace 操作，i.e., 把傳進去的值改變。比較好的做法是在 function 裡面寫好邏輯以後，再操作過後的檔案傳回來，比較好 debug，也不容易出錯。

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch3/ch3-1.py
> +
跟上面說的一樣，變數命名，常數也要改成 `THIS_IS_THE_CONSTANT` 的格式

2021-07-21 13:16 UTC, jamfly commented on u08410006/Week1/ch3/ch3-1.py
> +def normal(x, mu, sigma):
function 一律在上面，下面都是 main function 了。
範例：

```
def foo():
   pass

class Bar():
    pass

if __name__ == "__main__":
    bar = Bar()
```

2021-07-22 11:30 UTC, jamfly requested changes
又給了一輪 review，再修正吧

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +        h is like dx"""
Comment 可以改成這種形式嗎？
```
"""
If I really hate pressing `enter` and
typing all those hash marks, I could
just do this instead
"""
```

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +        return axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend for set_axes()"""
跟上面一樣

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +    # set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)
不要 commit comment 過後的扣

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +    axes=None,
如果可以的話塞進一個 dictionary 或是 dataclass 都會比較乾淨一些

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +        Each minibatch consists of a tuple of features and labels."""
跟上面一樣

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +            param -= lr * param.grad / batch_size
建議標上括號，可以幫助 context 理解。是 `(lr * param.grad) / batch_size` 還是 `lr * (param.grad / batch_size)`。對於運算子優先順序的人，也可以比較快理解這段扣。

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +        break
為什麼只印一個就跳開？

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +            lo = loss(net(X, w, b), y)  # Minibatch loss in `X` and `y`
不要用縮寫，變數命名寫長一點沒關係。`loss = squared_loss` 這邊會讓人誤會 loss 是一個值，function 前面要用動詞開頭。
例如：`calculate_loss()`，這樣你在寫的時候就可以寫成，```loss = calculate_loss(...)```。

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-3.py
> +        lo = loss(net(features), labels)
跟上面一樣

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-5.py
> +    return [text_labels[int(i)] for i in labels]
是 labels 還是 label_indices ? 看起來是 indices ，比較好的寫法是 `for index in label_indices` 不然會讓人誤會

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-5.py
> +        if titles:
`if titles is not None:`比較容易理解，不然我會猜 titles 是不是布林，另外布林值一率用 `is_` 開頭。

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-5.py
> +    return 4
也可以用 `os.cpu_count()` 然後傳一個參數進來調整，看是要用除的，還是怎樣。

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-5.py
> +    if resize:
改成 `resize is not None`

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-5.py
> +    batch_size = 256
`BATCH_SIZE = 256` 比較好

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-5.py
> +        break
為什麼只印一個？

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +THIS_IS_THE_CONSTANT_lr = 0.1  # used in updater
不是... 我是說 `LEARNING_RATE = 0.1`

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +def cross_entropy(y_hat, y):
沒有註解

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
這樣條件別人看不懂，`if len(y_hat.shape) > 1 and y_hat.shape[1] > 1` 要拆成 `你要條件名稱 = y_hat.shape[1] > 1`
`條件名稱 =  len(y_hat.shape) > 1` 然後用條件名稱去 and 這樣就很好懂

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    metric = Accumulator(3)
不要用魔術數字 3 給他個名稱

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +
如果要寫 assert 的話，要記得印 error message。

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +        break
為啥 break 掉？

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +
其實也可以考慮用 try catch

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +        break
為什麼又跳開？

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +        self.data = [0.0] * n
n 是啥？

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +        self.data = [a + float(b) for a, b in zip(self.data, args)]
a b 又是啥？

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    num_outputs = 10
`BATCH_SIZE = 256 NUM_INPUTS=784 NUM_OUTPUTS = 10`

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    W = torch.normal(
什麼是 W?

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    num_epochs = 10
`NUM_EPOCHS = 10`

2021-07-22 11:30 UTC, jamfly commented on u08410006/Week1/ch3/ch3-7.py
> +    num_epochs = 10
常數都要改喔

2021-07-22 17:44 UTC, U08410006 commented on u08410006/Week1/ch2/ch2-4.py
> +    axes=None,
對不起我不會改QAQQQ
我知道class是什麼，也有點概念，但這份code裡面的內容
我有點不知道怎麼改成class...

2021-07-22 17:45 UTC, U08410006 commented on u08410006/Week1/ch3/ch3-5.py
> +    return 4
對不起這邊我沒很懂QQQQQQ
我查了 os.cpu_count() 但我不知道要怎麼調整他...

2021-07-23 02:24 UTC, jamfly requested changes

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch2/ch2-4.py
> +    axes=None,
FYI, https://github.com/zedr/clean-code-python#function-arguments-2-or-fewer-ideally。另外這整份都滿好的，可以讀過一次。

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +    BATCH_SIZE = 10
要放在 main function 的最上面

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +    NUM_EPOCHS = 3
要放在 main function 的最上面

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +    calculate_loss = squared_loss
可不可以直接把原本 function 改成 calculate_loss 這個名字

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-2.py
> +    BATCH_SIZE = 10
剩下的 constant 也要改

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-3.py
> +    num_epochs = 3
constant 才對

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-5.py
> +    cpuCount = os.cpu_count()
不要用小駝峰，`cpu_count` 才對

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +LEARNING_RATE = 0.1  # used in updater
放在 main function 裏面

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    NUM_OUTPUTS = 10
```
BATCH_SIZE = 256
NUM_INPUTS = 784
NUM_OUTPUTS = 10

train_iter, test_iter = d2l.load_data_fashion_mnist(BATCH_SIZE)
```
一樣的放一起

2021-07-23 02:24 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    Weight = torch.normal(
Weight 大寫的話，會讓人誤會是 class

2021-07-23 04:08 UTC, jamfly requested changes

2021-07-23 04:08 UTC, jamfly commented on u08410006/Week1/ch3/ch3-6.py
> +    LEARNING_RATE = 0.1
比較推薦把 learning rate 傳進來，然後 constant 定義在外面

2021-07-23 04:10 UTC, jamfly commented
@U08410006 只剩下一兩個小問題，修正過後再 ping 我，沒問題就可以 merge 了

2021-07-24 06:50 UTC, merged