finish week1 progress
Sinica-SLAM/Intern-Training pull request #18
Opened 2021-07-26 17:32 UTC by coookie89

### Summary
> add week1 pytorch(ch2-ch3) examples & exercises
### Todo
- [x] ch2
- [x] ch3

2021-07-26 17:42 UTC, coookie89 commented
抱歉 請問右邊的Assignees跟Labels是要在pr還沒送出的時候設定嗎

2021-07-26 17:45 UTC, jamfly commented
> 抱歉 請問右邊的Assignees跟Labels是要在pr還沒送出的時候設定嗎

我來按即可

2021-07-26 17:46 UTC, jamfly commented
@coookie89 你可以參考其他人的，將練習改成 python script 不要用 notebook 嗎？

2021-07-26 17:48 UTC, coookie89 commented
好的！！

2021-07-26 17:49 UTC, jamfly commented
> 好的！！

然後順便翻一下 closed pr，看一下 comment，也許會有一些重複的錯誤你會犯。就稍微了解一下

2021-07-26 17:50 UTC, coookie89 commented
好的 我再改一下

2021-07-27 08:20 UTC, jamfly requested changes
一些小地方需要修正

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.2/exercise1.py
> +    m = data.isnull().sum(axis=0)  # 計算NaN每個col出現的次數
m 可以變成 `number_of_null` 之類的名稱，不然看的人會需要通靈

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.2/exercise1.py
> +    m = data.isnull().sum(axis=0)  # 計算NaN每個col出現的次數
因為你下面用到很多次 m 這個變數

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.2/exercise1.py
> +            temp = data.drop([index], axis=1)
不要叫 temp，他並沒有任何意義，叫 `droped_element` 之類的都好

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.2/exercise1.py
> +    temp = pd.get_dummies(data, dummy_na=True)
跟上面一樣

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.3/exercise6.py
> +    # print("\nA / A.sum(axis=1)==>\n",A / A.sum(axis=1))
不要 commit 被註解的 code

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.4/exercise1.py
> +    axes.grid()
function 已經有註解了，像是 `# 題目給的f(x)函式` 這種個人筆記可以考慮變更詳細的註解，或是把 function 名稱改得更有可讀性。這樣就不需要有這麼多不同的註解，希望可以拿掉個人的，留一份註解即可。

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.4/exercise1.py
> +    axes.grid()
並且不要 commit 被註解的 code

2021-07-27 08:20 UTC, jamfly commented on coookie89/Week1/ch2/2.4/exercise1.py
> +):  # 畫出數據(X,Y)的點
跟上面一樣

2021-07-27 08:21 UTC, jamfly commented
另外要記得在 readme 填上時間

2021-07-27 08:41 UTC, jamfly requested changes

2021-07-27 08:41 UTC, jamfly commented on coookie89/Week1/ch2/2.4/exercise1.py
> +def function(x):  # 題目給的f(x)函式, return y 值
可以跟下面的形式統一 """題目給的f(x)函式, return y 值"""

2021-07-27 08:41 UTC, jamfly commented on coookie89/Week1/ch2/2.4/exercise1.py
> +    if legend:
``` ìf legend is not None:``` 比較清楚

2021-07-27 08:51 UTC, jamfly approved these changes
LGTM!

2021-07-27 08:51 UTC, merged