Learning pytorch
Sinica-SLAM/Intern-Training pull request #19
Opened 2021-08-03 20:08 UTC by coookie89

### Summary
> add week2 pytorch(ch4-ch5) examples & exercises

### Todo
- [x] ch4
- [x] ch5

2021-08-04 04:32 UTC, jamfly requested changes
一些重複出現的小地方需要修正

2021-08-04 04:32 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise1.py
> +        lr = 0.1  # learning rate
可以放到上面變常數，其實 batch_size 還有前面的 input output 也可以是常數就是。

2021-08-04 04:32 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise1.py
> +        loss = nn.CrossEntropyLoss()
這邊改叫 loss_function 會比較好，loss 會讓人誤會他是被計算出來的 loss

2021-08-04 04:32 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise1.py
> +        loss = nn.CrossEntropyLoss()
甚至不用給個名字，直接塞進 function 裡面都是可以接受的

2021-08-04 04:32 UTC, jamfly commented on coookie89/Week2/ch4/4.3/exercise2.py
> +    )
可以寫成 function

2021-08-04 04:32 UTC, jamfly commented on coookie89/Week2/ch4/4.4/example.py
> +        losses = loss(out, y)
loss 改成 loss_function 比較可讀

2021-08-04 04:32 UTC, jamfly commented on coookie89/Week2/ch4/4.4/example.py
> +    trainer = torch.optim.SGD(net.parameters(), lr=0.01)
這邊的 lr 也可以變成參數

2021-08-04 04:32 UTC, jamfly commented on coookie89/Week2/ch4/4.5/example.py
> +    num_epochs, lr = 100, 0.003
改成參數吃進來會比較乾淨

2021-08-05 06:25 UTC, coookie89 commented on coookie89/Week2/ch4/4.2/exercise1.py
> +        lr = 0.1  # learning rate
是指放在main的最上面嗎
還是把它放在整份程式的最上面(當全域變數)

2021-08-05 06:48 UTC, coookie89 commented on coookie89/Week2/ch4/4.2/exercise1.py
> +        lr = 0.1  # learning rate
是改成THIS_IS_THE_num_epochs = 10
然後放程式最上面嗎！

2021-08-05 07:03 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise1.py
> +        lr = 0.1  # learning rate
`NUM_EPOCHS = 10`

2021-08-05 11:11 UTC, jamfly requested changes

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise1.py
> +
不要有空格，所有常數都排在一起

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise1.py
> +
不要有空格

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise2.py
> +    num_hiddens_2 = 128
跟上面的一樣可以改成常數

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.2/exercise2.py
> +        torch.randn(num_inputs, num_hiddens_1, requires_grad=True) * 0.01
不要用魔術數字 0.1，把 0.1 變成一個變數

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.3/exercise1.py
> +    # 兩層hidden layers
不要有空格

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.3/exercise1.py
> +
常數

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.3/exercise2.py
> +
不要有空格

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.3/exercise2.py
> +    num_epochs = 10
常數

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.3/exercise2.py
> +
不要有空格

2021-08-05 11:11 UTC, jamfly commented on coookie89/Week2/ch4/4.3/exercise2.py
> +
像這種情況 建議把 else 也寫完整，有時候會出現沒想到的 case，這可以幫助 debug
```
else:
    print(f"{net_id=}")
```

2021-08-08 15:48 UTC, jamfly approved these changes

2021-08-08 15:49 UTC, merged

2021-08-08 15:49 UTC, jamfly commented
README 忘了寫日期，但已經 merge 了，下一條 PR 再補吧